### ISSUE TITLE
how to run this project in pycharm

### ISSUE THREAD

**Issue by vamshinoora** [arunvalluthadam/has-job-site#1]

**Comment by arunvalluthadam** [comment]
Just clone this repository and open it in pycharm.
Press Ctrl+Alt+R, and enter `runserver` in the `manage.py` console.
Then it is ready to use.
please check the [link](https://www.jetbrains.com/help/pycharm/creating-and-running-your-first-django-project.html#launch-server) if you suffer any issues running this project in pycharm.
